# Generated by Django 4.1.5 on 2023-02-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zendeskticket",
            name="zendesk_ticket_id",
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
