# Generated by Django 4.1.5 on 2023-02-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0002_zendeskticket_zendesk_ticket_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="zendeskticket", name="updated_at",),
        migrations.AlterField(
            model_name="zendeskticket",
            name="priority",
            field=models.PositiveIntegerField(
                choices=[(1, "Low"), (2, "Normal"), (3, "High"), (4, "Urgent")],
                default=1,
                help_text="5 means top priority",
            ),
        ),
    ]
