# Generated by Django 4.1.5 on 2023-02-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0005_rename_prioritys_zendeskticket_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zendeskticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "low"),
                    ("normal", "normal"),
                    ("high", "high"),
                    ("urgent", "urgent"),
                ],
                default="Low",
                max_length=20,
            ),
        ),
    ]
